server:
  port: 8066
  servlet:
    context-path: /api

#  DataSource Config
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: 182.61.11.252
    port: 6379
    database: 9
    password: HnYU0++qi1gF*7su%syh
  datasource:
    dynamic:
      druid:
        initial-size: 2
        max-active: 50
        max-wait: 60000
        min-evictable-idle-time-millis: 25200000
        min-idle: 2
        test-on-borrow: false
        test-on-return: false
        test-while-idle: false
        time-between-eviction-runs-millis: 60000
        validation-query: select 'x'
      primary: chatgptdemodb #设置默认的数据源或者数据源组,默认值即为master
      strict: true #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        chatgptdemodb:
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.alibaba.druid.pool.DruidDataSource
          url: jdbc:mysql://bj-cynosdbmysql-grp-o9u7ldum.sql.tencentcdb.com:21457/chatgpt_demo_db?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
          username: root
          password: hh%Gy&rTYM@oepc6
